language: php

sudo: false

dist: trusty

php:
  - 7.2
  - 7.3
  - nightly
  - hhvm

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

before_script:
  - composer self-update || true
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader

script: vendor/bin/phpunit
